LANGUAGES = {
    'en': {
        'file': 'File',
        'new': 'New',
        'open': 'Open',
        'save': 'Save',
        'save_as': 'Save as...',
        'exit': 'Exit',
        'view': 'View',
        'dark_theme': 'Dark Theme',
        'light_theme': 'Light Theme',
        'full_v': 'Full Version',
        'light_v': 'Light Version',
        'save_file': 'Save File',        
        'quest_bef_cls': 'Do you want to save this file?',
        'all_files': 'All files',
        'lang': 'English',
        'lang_menu': 'Language',
        'dnld': 'Download',
        'send': 'Send',
        'send_link': 'Send via link...',
        'success': 'Success',
        'menubar_code': 'No saved files',
        'compile': 'Compile',
        'con_test': 'Test connection',
        'add': 'Add',
        'del': 'Delete',
        'con_name': 'Connection name',
        'login': 'Login',
        'adr': 'Robot adress',
        'saved_servs': 'Saved servers',
        'refresh': 'Refresh list',
        'paste': 'Paste',
        'copy': 'Copy',
        'cut': 'Cut',
        'select_all': 'Select all',
        'serv_already': 'Server already exists',
        'confirm': 'Confirmation',
        'err': 'Error',
        'del_serv': 'Delete server',
        'change_dir': 'Change files dir',
        'pass': 'Password',
        'robot': 'Robot',
        'r_backup': 'Robot backup',
        'open_folder': 'Open folder...',
        'create_folder': 'Create folder',
        'compiled_success': 'Compilation success!',
        'compiled': 'Compiled!',
        'compilation_error': 'Error with compilation',
        'inf': 'Information',
        'no_select_server': 'Server is not selected',
        'warn': 'Warning',
        'cant_send_folder': "Can't send the folder!",
        'send_confirm': 'Confirmation of sending',
        'to_server': 'To server',
        'u_sure_to_send': 'Are you sure about sending the file',
        'sending_file': 'File sending',
        'was_success': 'was success',
        'couldnt_send_file': "Couldn't send file",
        'choice_folder': 'Choice a folder',
        'folder_name': 'Folder name',
        'enter_folder_name': 'Enter the folder name',
        'empty_name': 'Empty name',
        'name_empty': 'Empty name of folder',
        'connection_error': 'Connection error',
        'couldnt_download_file': "Couldn't download file",
        'couldnt_open_file': "Couldn't open file",
        'filter': '.ls filter',
        'couldnt_connect': "Couldn't connect",
        'timeout': 'Conenction timeout',
        'con_success': 'Connection is established',
        'but_no_files': 'but it was not possible to get a list of files',
        'found': 'Found',
        'files': 'files',
        'no_adress': 'Address not specified',
        'no_name_or_adress': 'Name or address is missing!'

    },
    'ru': {
        'file': 'Файл',
        'new': 'Новый',
        'open': 'Открыть',
        'save': 'Сохранить',
        'save_as': 'Сохранить как...',
        'exit': 'Выход',
        'view': 'Вид',
        'dark_theme': 'Тёмная тема',
        'light_theme': 'Светлая тема',
        'full_v': 'Полный вид',
        'light_v': 'Упрощённый вид',
        'save_file': 'Сохранить файл',        
        'quest_bef_cls': 'Вы хотите сохранить изменения перед созданием нового?',
        'all_files': 'Все файлы',
        'lang': 'Русский',
        'lang_menu': 'Язык',
        'dnld': 'Скачать',
        'send': 'Отправить',
        'send_link': 'Отправить по ссылке...',
        'success': 'Успех',
        'menubar_code': 'Нет сохранённого файла',
        'compile': 'Скомпилировать',
        'con_test': 'Тест соединения',
        'add': 'Добавить',
        'del': 'Удалить',
        'con_name': 'Название подключения',
        'login': 'Логин', 
        'adr': 'Адрес робота',
        'saved_servs': 'Сохранённые сервера',
        'refresh': 'Обновить список',
        'paste': 'Вставить',
        'copy': 'Копировать',
        'cut': 'Вырезать',
        'select_all': 'Выбрать всё',
        'serv_already': 'Сервер уже добавлен',
        'confirm': 'Подтверждение',
        'err': 'Ошибка',
        'del_serv': 'Удалить сервер',
        'change_dir': 'Изменить путь к файлам',
        'pass': 'Пароль',
        'robot': 'Робот',
        'r_backup': 'Бэкап робота',
        'open_folder': 'Открыть папку...',
        'create_folder': 'Создать папку',
        'compiled_success': 'Успешная компиляция!',
        'compiled': 'Скомпилировано!',
        'compilation_error': 'Ошибка компиляции',
        'inf': 'Информация',
        'no_select_server': 'Сервер не выбран!',
        'warn': 'Предупреждение',
        'cant_send_folder': "Нельзя отправить папку!",
        'send_confirm': 'Подтверждение отправки',
        'to_server': 'На сервер',
        'u_sure_to_send': 'Вы уверены в отправке файла',
        'sending_file': 'Отправка файла',
        'was_success': 'прошла успешно',
        'couldnt_send_file': "Не удалось отправить файл",
        'choice_folder': 'Выбрать папку',
        'folder_name': 'Имя папки',
        'enter_folder_name': 'Введите имя папки',
        'empty_name': 'Пустое имя',
        'name_empty': 'Не введено имя папки',
        'connection_error': 'Ошибка соединения',
        'couldnt_download_file': "Не удалось скачать файл",
        'couldnt_open_file': "Не удалось открыть файл",
        'filter': '.ls фильтр',
        'couldnt_connect': "Не удалось подключиться",
        'timeout': 'Время вышло',
        'con_success': 'Соединение установлено',
        'but_no_files': 'но не удалось получить файлы',
        'found': 'Найдено',
        'files': 'файлов',
        'no_adress': 'Адрес не указан',
        'no_name_or_adress': 'Не указано имя или адрес!'
    }
}

SINTAX_WORDS = {
'keywords': [
            'IF', 'WAIT', 'CALL', 'PAUSE', 'ENDIF', 'ELSE',
            'THEN', 'SKIP', 'JMP',
            'RUN', 'L', 'J',
            ],
'logic': [
         'AND', 'OR', 'ON', 'OFF',
         ],
'datas': [
         'DO', 'DI', 'F', 'R', 'P', 'PR',
         ],
}

CURRENT_LANGUAGE = 'en'  # by default