LANGUAGES = {
    'en': {
        'file': 'File',
        'new': 'New',
        'open': 'Open',
        'save': 'Save',
        'save_as': 'Save as...',
        'exit': 'Exit',
        'view': 'View',
        'dark_theme': 'Dark Theme',
        'light_theme': 'Light Theme',
        'full_v': 'Full Version',
        'light_v': 'Light Version',
        'save_file': 'Save File',        
        'quest_bef_cls': 'Do you want to save this file?',
        'all_files': 'All files',
        'lang': 'English',
        'lang_menu': 'Language',
        'dnld': 'Download',
        'send': 'Send',
        'send_link': 'Send via link...',
        'success': 'Success',
        'suc_dnld': ' downloaded.',
        'suc_upl': ' uploaded.',
        'menubar_code': 'No saved files',
        'compile': 'Compile',
        'con_test': 'Test connection',
        'add': 'Add',
        'del': 'Delete',
        'con_name': 'Connection name',
        'login': 'Login',
        'adr': 'Robot adress',
        'back_file': '←',
        'saved_servs': 'Saved servers',
        'refresh': 'Refresh list',
        'paste': 'Paste',
        'copy': 'Copy',
        'cut': 'Cut',
        'select_all': 'Select all',
        'serv_already': 'Server already exists',
        'confirm': 'Confirmation',
        'err': 'Error',
        'del_serv': 'Delete server',
        'change_dir': 'Change files dir',
        'pass': 'Password'
    },
    'ru': {
        'file': 'Файл',
        'new': 'Новый',
        'open': 'Открыть',
        'save': 'Сохранить',
        'save_as': 'Сохранить как...',
        'exit': 'Выход',
        'view': 'Вид',
        'dark_theme': 'Тёмная тема',
        'light_theme': 'Светлая тема',
        'full_v': 'Полный вид',
        'light_v': 'Упрощённый вид',
        'save_file': 'Сохранить файл',        
        'quest_bef_cls': 'Вы хотите сохранить изменения перед созданием нового?',
        'all_files': 'Все файлы',
        'lang': 'Русский',
        'lang_menu': 'Язык',
        'dnld': 'Скачать',
        'send': 'Отправить',
        'send_link': 'Отправить по ссылке...',
        'success': 'Успех',
        'suc_dnld': ' скачан.',
        'suc_upl': ' отправлен.',
        'menubar_code': 'Нет сохранённого файла',
        'compile': 'Скомпилировать',
        'con_test': 'Тест соединения',
        'add': 'Добавить',
        'del': 'Удалить',
        'con_name': 'Название подключения',
        'login': 'Логин', 
        'adr': 'Адрес робота',
        'back_file': '←',
        'saved_servs': 'Сохранённые сервера',
        'refresh': 'Обновить список',
        'paste': 'Вставить',
        'copy': 'Копировать',
        'cut': 'Вырезать',
        'select_all': 'Выбрать всё',
        'serv_already': 'Сервер уже добавлен',
        'confirm': 'Подтверждение',
        'err': 'Ошибка',
        'del_serv': 'Удалить сервер',
        'change_dir': 'Изменить путь к файлам',
        'pass': 'Пароль'
    }
}

SINTAX_WORDS = {
'keywords': [
            'IF', 'WAIT', 'CALL', 'PAUSE', 'ENDIF', 'ELSE',
            'THEN', 'SKIP', 'JMP',
            'RUN', 'L', 'J',
            ],
'logic': [
         'AND', 'OR', 'ON', 'OFF',
         ],
'datas': [
         'DO', 'DI', 'F', 'R', 'P', 'PR',
         ],
}

CURRENT_LANGUAGE = 'ru'  # by default